### PR TITLE
chore: Decaffeinate

### PR DESCRIPTION
**Pull request by ffflorian**
This PR will
* remove CoffeeScript
* add a `files` entry to package.json to avoid publishing unrelated files (e.g. `.travis.yml`)

### CODE REVIEW

**Comment by wdavidw** [comment]
Thank you but I kept the test in Coffee on purpose, there much more readable.

**Comment by wdavidw** [comment]
Also, why did you remove the "file" field on package.json, is it a mistake?

**Comment by wdavidw** [comment]
Sorry, I misread the diff (and your description), I'm very surprise there was no "file" field before, definitely a mistake. Could you submit a new PR with only this part (as well as your contributor addition). Thank you.

**Comment by ffflorian** [comment]
Sure: https://github.com/adaltas/node-csv/pull/248

**Pull request closed without merging**
