### PR TITLE
feat: treat omitted columns as null #307

### PR DESCRIPTION
**Pull request by gregfenton**
Adding the option `null_if_omitted`

### CODE REVIEW

**Comment by wdavidw** [comment]
Hi @gregfenton 

The PR quality is impressive. I am however questioning wether we shall introduce a new option.

The behavior of the proposed option is the same as setting cast to `(value, {quoting}) =>  value === '' && !quoting ? null : value`.

I agree that understanding advanced usages of cast may be difficult but we can't introduce new option of every usage. A better approach to me is to improve the documentation:
- The [cast](https://csv.js.org/parse/options/cast/) page could be more clear and incorporate additional samples
- The [recipes](https://csv.js.org/parse/recipes/) section could be a good fit to describe the intended behavior and its solution using the native cast option.

**Comment by gregfenton** [comment]
Hi David,

I'm good with either approach.

I was looking for this capability so that I could remove a looping
construct from my code.  I found the Issue suggesting a new option and
the test case.  I wrote code :)

I had not considered the power of `cast`.  Docs & recipes enhancements seem
a more logical approach than a one-off option.

Thanks for the consideration.  Feel free to reject the PR.

Cheers,
Greg Fenton
--
email: ***@***.*** ***@***.***>*
linkedin: *http://ca.linkedin.com/in/fentongreg*
<http://ca.linkedin.com/in/fentongreg>
twitter: ***@***.****

**Comment by gregfenton** [comment]
Better to "fix" via docs & recipes than to add a whole new option for this.

**Comment by wdavidw** [comment]
Thanks again @gregfenton, it gives me pains to reject such a nicely polished PR :)

**Pull request closed without merging**
